version: "3.8"

services:
  ros-master:
    build:
      context: ./master-node
    container_name: ros-master-container
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://172.22.0.2:11311
      - ROS_IP=172.22.0.2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      ros_network:
        ipv4_address: 172.22.0.2

  ros-airsim:
    build:
      context: ./airsim-node
    container_name: ros-airsim-container
    depends_on:
      - ros-master
    volumes:
      - ./airsim-node/airsim_package:/catkin_ws/src/airsim_package/
    environment:
      - ROS_MASTER_URI=http://172.22.0.2:11311
      - ROS_IP=172.22.0.3
    networks:
      ros_network:
        ipv4_address: 172.22.0.3

  ros-depth-estimation:
    build:
      context: ./depth-estimation-node
    container_name: ros-depth-estimation-container
    depends_on:
      - ros-master
    volumes:
      - ./depth-estimation-node/depth_estimation_package:/catkin_ws/src/depth_estimation_package/
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://172.22.0.2:11311
      - ROS_IP=172.22.0.4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    networks:
      ros_network:
        ipv4_address: 172.22.0.4
    
  ros-mapper-nav:
    build:
      context: ./mapper-nav-node
    container_name: ros-mapper-nav-container
    depends_on:
      - ros-master
    volumes:
      - ./mapper-nav-node/nav:/catkin_ws/src/nav
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://172.22.0.2:11311
      - ROS_IP=172.22.0.5
    networks:
      ros_network:
        ipv4_address: 172.22.0.5

networks:
  ros_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
